import { ApiError, fail, json, ok, parsePaging, readJson } from './http.js'
import { requireAdmin, requireAuth, requireCustomer, requireOwnership } from './auth.js'
import { categorySchema, contentSchema, idSchema, orderStatusSchema, productSchema, profileSchema, projectSchema, quoteRequestSchema, quoteStatusSchema, uploadIntentSchema, validate } from './validation.js'
import { createObjectKey, validateUpload } from './storage.js'

const routes = (pathname) => pathname.replace(/^\/api/, '').split('/').filter(Boolean)
const publicProductFields = 'id, name, slug, short_description, description, category_id, pricing_type, starting_price, currency, production_lead_time'
export function createApi({ db, authenticate = async () => null, logger = console, storage }) {
  return async function api(request) {
    const started = Date.now(); const url = new URL(request.url); const parts = routes(url.pathname)
    try {
      let response
      if (request.method === 'GET' && parts[0] === 'products' && !parts[1]) { const { limit, offset } = parsePaging(url); const rows = await db.query(`SELECT ${publicProductFields} FROM public.products WHERE status='published' ORDER BY published_at DESC NULLS LAST LIMIT $1 OFFSET $2`, [limit, offset]); response = ok(rows) }
      else if (request.method === 'GET' && parts[0] === 'products' && parts[1]) { const rows = await db.query(`SELECT ${publicProductFields} FROM public.products WHERE slug=$1 AND status='published'`, [parts[1]]); if (!rows[0]) throw new ApiError(404, 'not_found', 'Product not found.'); response = ok(rows[0]) }
      else if (request.method === 'GET' && parts[0] === 'categories') response = ok(await db.query("SELECT id,name,slug,parent_id,description FROM public.categories WHERE is_published=true ORDER BY sort_order,name"))
      else if (request.method === 'GET' && parts[0] === 'services') response = ok(await db.query("SELECT id,name,slug,description FROM public.categories WHERE is_published=true ORDER BY sort_order,name"))
      else if (request.method === 'GET' && parts[0] === 'projects' && !parts[1]) { const { limit, offset } = parsePaging(url); const rows = await db.query("SELECT id,title,slug,description,completed_on FROM public.projects WHERE is_published=true ORDER BY completed_on DESC NULLS LAST LIMIT $1 OFFSET $2", [limit, offset]); response = ok(rows) }
      else if (request.method === 'GET' && parts[0] === 'projects' && parts[1]) { const rows = await db.query("SELECT id,title,slug,description,completed_on FROM public.projects WHERE is_published=true AND slug=$1", [parts[1]]); if (!rows[0]) throw new ApiError(404, 'not_found', 'Project not found.'); response = ok(rows[0]) }
      else if (request.method === 'GET' && parts[0] === 'content' && parts[1] === 'public') response = ok(await db.query("SELECT section,entry_key,value FROM public.content_entries WHERE is_published=true"))
      else if (request.method === 'GET' && parts[0] === 'me') { const actor = await requireCustomer(request, authenticate); response = ok(actor.profile) }
      else if (request.method === 'POST' && parts[0] === 'me') { const actor = await requireAuth(request, authenticate); const body = validate(profileSchema, await readJson(request)); if (actor.profile) throw new ApiError(409, 'profile_exists', 'A profile already exists.'); const rows = await db.query('INSERT INTO public.user_profiles(auth_user_id,role,full_name,phone,company_name) VALUES($1,$2,$3,$4,$5) RETURNING id,auth_user_id,role,full_name,phone,company_name', [actor.authUserId,'customer',body.fullName,body.phone || null,body.companyName || null]); response = ok(rows[0], 201) }
      else if (request.method === 'PATCH' && parts[0] === 'me') { const actor = await requireCustomer(request, authenticate); const body = validate(profileSchema, await readJson(request)); const rows = await db.query('UPDATE public.user_profiles SET full_name=$1,phone=$2,company_name=$3 WHERE id=$4 RETURNING id,auth_user_id,role,full_name,phone,company_name', [body.fullName,body.phone || null,body.companyName || null,actor.profile.id]); response = ok(rows[0]) }
      else if (request.method === 'GET' && parts[0] === 'orders' && !parts[1]) { const actor = await requireCustomer(request, authenticate); response = ok(await db.query('SELECT id,order_number,status_code,total_amount,currency,created_at FROM public.orders WHERE customer_id=$1 ORDER BY created_at DESC', [actor.profile.id])) }
      else if (request.method === 'GET' && parts[0] === 'orders' && parts[1]) { const actor = await requireCustomer(request, authenticate); const row = (await db.query('SELECT id,customer_id,order_number,status_code,total_amount,currency,created_at FROM public.orders WHERE id=$1', [validate(idSchema, parts[1])]))[0]; response = ok(requireOwnership(row, actor)) }
      else if (request.method === 'GET' && parts[0] === 'quotes') { const actor = await requireCustomer(request, authenticate); response = ok(await db.query('SELECT id,request_number,status_code,created_at FROM public.quote_requests WHERE customer_id=$1 ORDER BY created_at DESC', [actor.profile.id])) }
      else if (request.method === 'POST' && parts[0] === 'quote-requests') { const body = validate(quoteRequestSchema, await readJson(request)); const actor = await authenticate(request); const requestNumber = `QR-${Date.now()}-${crypto.randomUUID().slice(0, 6).toUpperCase()}`; const rows = await db.query('INSERT INTO public.quote_requests(request_number,customer_id,contact_name,contact_email,contact_phone,project_brief,status_code) VALUES ($1,$2,$3,$4,$5,$6,$7) RETURNING id,request_number,status_code,created_at', [requestNumber, actor?.profile?.id || null, body.contactName, body.contactEmail, body.contactPhone || null, body.projectBrief, 'submitted']); response = ok(rows[0], 201) }
      else if (request.method === 'POST' && parts[0] === 'files' && parts[1] === 'upload-intent') response = await createUploadIntent(request, db, authenticate, storage)
      else if (request.method === 'GET' && parts[0] === 'files' && parts[1] && parts[2] === 'access') response = await getFileAccess(request, parts[1], db, authenticate, storage)
      else if (parts[0] === 'admin') response = await adminApi(request, parts.slice(1), db, authenticate)
      else throw new ApiError(404, 'not_found', 'Endpoint not found.')
      logger.info?.({ method: request.method, path: url.pathname, status: response.status, ms: Date.now() - started }, 'api_request')
      return response
    } catch (error) { logger.error?.({ method: request.method, path: url.pathname, code: error.code, ms: Date.now() - started }, 'api_error'); return fail(error) }
  }
}
async function adminApi(request, parts, db, authenticate) {
  const admin = await requireAdmin(request, authenticate)
  if (request.method === 'POST' && parts[0] === 'products') { const body = validate(productSchema, await readJson(request)); const rows = await db.query('INSERT INTO public.products(name,slug,category_id,short_description,description,pricing_type,starting_price,is_configurable,quote_required,status) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING id,slug,status', [body.name,body.slug,body.categoryId || null,body.shortDescription || null,body.description || null,body.pricingType,body.startingPrice ?? null,body.isConfigurable,body.quoteRequired,body.status]); return ok(rows[0], 201) }
  if (request.method === 'PATCH' && parts[0] === 'products' && parts[1]) { const body = validate(productSchema, await readJson(request)); const rows = await db.query('UPDATE public.products SET name=$1,slug=$2,category_id=$3,short_description=$4,description=$5,pricing_type=$6,starting_price=$7,is_configurable=$8,quote_required=$9,status=$10 WHERE id=$11 RETURNING id,slug,status', [body.name,body.slug,body.categoryId || null,body.shortDescription || null,body.description || null,body.pricingType,body.startingPrice ?? null,body.isConfigurable,body.quoteRequired,body.status,validate(idSchema,parts[1])]); if (!rows[0]) throw new ApiError(404,'not_found','Product not found.'); return ok(rows[0]) }
  if (request.method === 'DELETE' && parts[0] === 'products' && parts[1]) { const rows = await db.query("UPDATE public.products SET status='archived' WHERE id=$1 RETURNING id,status", [validate(idSchema,parts[1])]); if (!rows[0]) throw new ApiError(404,'not_found','Product not found.'); return ok(rows[0]) }
  if (request.method === 'GET' && parts[0] === 'categories') return ok(await db.query('SELECT id,name,slug,parent_id,description,sort_order,is_published FROM public.categories ORDER BY sort_order,name'))
  if (request.method === 'POST' && parts[0] === 'categories') { const body = validate(categorySchema, await readJson(request)); const rows = await db.query('INSERT INTO public.categories(name,slug,parent_id,description,sort_order,is_published) VALUES($1,$2,$3,$4,$5,$6) RETURNING id,slug', [body.name,body.slug,body.parentId || null,body.description || null,body.sortOrder,body.isPublished]); return ok(rows[0],201) }
  if (request.method === 'PATCH' && parts[0] === 'categories' && parts[1]) { const body = validate(categorySchema, await readJson(request)); const rows = await db.query('UPDATE public.categories SET name=$1,slug=$2,parent_id=$3,description=$4,sort_order=$5,is_published=$6 WHERE id=$7 RETURNING id,slug', [body.name,body.slug,body.parentId || null,body.description || null,body.sortOrder,body.isPublished,validate(idSchema,parts[1])]); if (!rows[0]) throw new ApiError(404,'not_found','Category not found.'); return ok(rows[0]) }
  if (request.method === 'GET' && parts[0] === 'orders') { const { limit, offset } = parsePaging(new URL(request.url)); return ok(await db.query('SELECT id,order_number,customer_id,status_code,total_amount,currency,created_at FROM public.orders ORDER BY created_at DESC LIMIT $1 OFFSET $2',[limit,offset])) }
  if (request.method === 'GET' && parts[0] === 'quotes') { const { limit, offset } = parsePaging(new URL(request.url)); return ok(await db.query('SELECT id,request_number,customer_id,status_code,contact_name,contact_email,created_at FROM public.quote_requests ORDER BY created_at DESC LIMIT $1 OFFSET $2',[limit,offset])) }
  if (request.method === 'PATCH' && parts[0] === 'quotes' && parts[1]) { const body = validate(quoteStatusSchema,await readJson(request)); const rows = await db.query('UPDATE public.quotes SET status_code=$1,total_amount=COALESCE($2,total_amount),valid_until=$3 WHERE id=$4 RETURNING id,status_code,total_amount', [body.statusCode,body.totalAmount ?? null,body.validUntil ?? null,validate(idSchema,parts[1])]); if (!rows[0]) throw new ApiError(404,'not_found','Quote not found.'); return ok(rows[0]) }
  if (request.method === 'POST' && parts[0] === 'projects') { const body = validate(projectSchema,await readJson(request)); const rows = await db.query('INSERT INTO public.projects(title,slug,category_id,client_name,location,description,completed_on,is_featured,is_published,published_at) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,CASE WHEN $9 THEN now() ELSE NULL END) RETURNING id,slug',[body.title,body.slug,body.categoryId || null,body.clientName || null,body.location || null,body.description || null,body.completedOn || null,body.isFeatured,body.isPublished]); return ok(rows[0],201) }
  if (request.method === 'PATCH' && parts[0] === 'projects' && parts[1]) { const body = validate(projectSchema,await readJson(request)); const rows = await db.query('UPDATE public.projects SET title=$1,slug=$2,category_id=$3,client_name=$4,location=$5,description=$6,completed_on=$7,is_featured=$8,is_published=$9,published_at=CASE WHEN $9 AND published_at IS NULL THEN now() WHEN NOT $9 THEN NULL ELSE published_at END WHERE id=$10 RETURNING id,slug',[body.title,body.slug,body.categoryId || null,body.clientName || null,body.location || null,body.description || null,body.completedOn || null,body.isFeatured,body.isPublished,validate(idSchema,parts[1])]); if (!rows[0]) throw new ApiError(404,'not_found','Project not found.'); return ok(rows[0]) }
  if (request.method === 'PATCH' && parts[0] === 'content' && parts[1]) { const body = validate(contentSchema,await readJson(request)); const rows = await db.query('UPDATE public.content_entries SET value=$1,is_published=COALESCE($2,is_published) WHERE section=$3 RETURNING id,section,entry_key,value,is_published',[JSON.stringify(body.value),body.isPublished ?? null,parts[1]]); if (!rows.length) throw new ApiError(404,'not_found','Content section not found.'); return ok(rows) }
  if (request.method === 'PATCH' && parts[0] === 'orders' && parts[1] && parts[2] === 'status') { const body = validate(orderStatusSchema, await readJson(request)); const id = validate(idSchema, parts[1]); const [rows, history] = await db.transaction((transaction) => [transaction.query('UPDATE public.orders SET status_code=$1 WHERE id=$2 RETURNING id,order_number,status_code', [body.statusCode,id]), transaction.query('INSERT INTO public.order_status_history(order_id,status_code,changed_by_auth_user_id,note) SELECT id,$1,$2,$3 FROM public.orders WHERE id=$4 RETURNING id', [body.statusCode,admin.authUserId,body.note || null,id])]); if (!rows[0] || !history[0]) throw new ApiError(404,'not_found','Order not found.'); return ok(rows[0]) }
  throw new ApiError(404, 'not_found', 'Admin endpoint not found.')
}
async function createUploadIntent(request, db, authenticate, storage) {
  const actor = await requireCustomer(request, authenticate); const body = validate(uploadIntentSchema, await readJson(request)); validateUpload(body)
  if (body.orderItemId) { const owned = await db.query('SELECT oi.id FROM public.order_items oi JOIN public.orders o ON o.id=oi.order_id WHERE oi.id=$1 AND o.customer_id=$2',[body.orderItemId,actor.profile.id]); if (!owned[0]) throw new ApiError(404,'not_found','Order item not found.') }
  if (body.quoteRequestId) { const owned = await db.query('SELECT id FROM public.quote_requests WHERE id=$1 AND customer_id=$2',[body.quoteRequestId,actor.profile.id]); if (!owned[0]) throw new ApiError(404,'not_found','Quote request not found.') }
  const objectKey = createObjectKey({ purpose: body.purpose, extension: body.filename.split('.').pop() }); const visibility = body.purpose === 'customer_artwork' || body.purpose === 'design_proof' ? 'private' : 'public'
  const [asset] = await db.query('INSERT INTO public.media_assets(object_key,original_filename,mime_type,byte_size,visibility,purpose,uploaded_by_auth_user_id) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id,object_key',[objectKey,body.filename,body.mimeType,body.byteSize,visibility,body.purpose,actor.authUserId])
  const upload = await storage.createUploadUrl({ objectKey, mimeType: body.mimeType, byteSize: body.byteSize, visibility }); return ok({ asset, upload },201)
}
async function getFileAccess(request, assetId, db, authenticate, storage) {
  const id = validate(idSchema,assetId); const asset = (await db.query('SELECT id,object_key,visibility,purpose FROM public.media_assets WHERE id=$1',[id]))[0]; if (!asset) throw new ApiError(404,'not_found','File not found.')
  if (asset.visibility === 'private') { const actor = await requireCustomer(request,authenticate); if (actor.profile.role !== 'admin') { const owned = await db.query('SELECT 1 FROM public.order_item_media oim JOIN public.order_items oi ON oi.id=oim.order_item_id JOIN public.orders o ON o.id=oi.order_id WHERE oim.media_id=$1 AND o.customer_id=$2 UNION ALL SELECT 1 FROM public.quote_request_media qrm JOIN public.quote_requests qr ON qr.id=qrm.quote_request_id WHERE qrm.media_id=$1 AND qr.customer_id=$2 LIMIT 1',[id,actor.profile.id]); if (!owned[0]) throw new ApiError(404,'not_found','File not found.') } }
  const download = await storage.createDownloadUrl({ objectKey: asset.object_key, visibility: asset.visibility }); return ok({ download })
}
