import { z } from 'zod'
import { ApiError } from './http.js'
export const idSchema = z.string().uuid()
export const quoteRequestSchema = z.object({ contactName: z.string().trim().min(2).max(120), contactEmail: z.string().trim().email().max(254), contactPhone: z.string().trim().max(40).optional(), projectBrief: z.string().trim().min(10).max(10000) })
export const profileSchema = z.object({ fullName: z.string().trim().min(2).max(160), phone: z.string().trim().max(40).optional(), companyName: z.string().trim().max(160).optional() })
export const productSchema = z.object({ name: z.string().trim().min(2).max(180), slug: z.string().trim().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/), categoryId: idSchema.nullable().optional(), shortDescription: z.string().trim().max(300).nullable().optional(), description: z.string().trim().max(30000).nullable().optional(), pricingType: z.enum(['fixed','configurable','quote_only']), startingPrice: z.coerce.number().nonnegative().nullable().optional(), isConfigurable: z.boolean().default(false), quoteRequired: z.boolean(), status: z.enum(['draft','published','archived']).default('draft') }).superRefine((value, context) => { if (value.pricingType === 'fixed' && value.startingPrice == null) context.addIssue({ code: 'custom', path: ['startingPrice'], message: 'Fixed-price products require a starting price.' }); if ((value.pricingType === 'quote_only') !== value.quoteRequired) context.addIssue({ code: 'custom', path: ['quoteRequired'], message: 'quoteRequired must match quote_only pricing.' }) })
export const orderStatusSchema = z.object({ statusCode: z.string().regex(/^[a-z_]+$/), note: z.string().trim().max(2000).optional() })
export const categorySchema = z.object({ name: z.string().trim().min(2).max(120), slug: z.string().trim().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/), parentId: idSchema.nullable().optional(), description: z.string().trim().max(3000).nullable().optional(), sortOrder: z.coerce.number().int().nonnegative().default(0), isPublished: z.boolean().default(false) })
export const projectSchema = z.object({ title: z.string().trim().min(2).max(180), slug: z.string().trim().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/), categoryId: idSchema.nullable().optional(), clientName: z.string().trim().max(180).nullable().optional(), location: z.string().trim().max(180).nullable().optional(), description: z.string().trim().max(30000).nullable().optional(), completedOn: z.string().date().nullable().optional(), isFeatured: z.boolean().default(false), isPublished: z.boolean().default(false) })
export const contentSchema = z.object({ value: z.record(z.string(), z.unknown()), isPublished: z.boolean().optional() })
export const quoteStatusSchema = z.object({ statusCode: z.string().regex(/^[a-z_]+$/), totalAmount: z.coerce.number().nonnegative().optional(), validUntil: z.string().date().nullable().optional() })
export const uploadIntentSchema = z.object({ filename: z.string().trim().min(1).max(255), mimeType: z.string().trim().max(120), byteSize: z.coerce.number().int().positive(), purpose: z.enum(['product_image','project_image','customer_artwork','design_proof','website_asset']), orderItemId: idSchema.optional(), quoteRequestId: idSchema.optional() })
export function validate(schema, value) { const parsed = schema.safeParse(value); if (!parsed.success) throw new ApiError(422, 'validation_failed', 'One or more values are invalid.', parsed.error.flatten().fieldErrors); return parsed.data }
